### CASES ENDPOINTS
POST http://localhost:3000/api/cases HTTP/1.1
Content-Type: application/json
#x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU2ODc0Nzg0NTEiLCJpYXQiOjE2OTgyNTIwMzEsImV4cCI6MTY5ODMzODQzMX0.kBgII6y9lrUEw09aIQ4kVpA_Tbfgd69jZ23zcUwN7X8

{
    "nombreCaso": "Caso 002",
    "acosador": "Ana Acosadora",
    "telAcosador": "601758865",
    "desc": "Me acosa por la calle, en redes sociales y por teléfono"
}

###
GET http://localhost:3000/api/cases HTTP/1.1

###
GET http://localhost:3000/api/cases/65383b2f7f9e01c0a676d1cb HTTP/1.1

###
PUT http://localhost:3000/cases/api/65383b2f7f9e01c0a676d1cb HTTP/1.1
Content-Type: application/json

{
    "acosador": "Juan Adorador",
    "telAcosador": "1234567825",
    "desc": "Me acosa por la calle, en redes sociales y por teléfono"
}

###
DELETE http://localhost:3000/cases/65383aaaf7f8578f55a25682 HTTP/1.1



### USERS AUTH ENDPOINTS

POST http://localhost:3000/api/auth/singup HTTP/1.1
Content-Type: application/json

{
    "nombre": "Malia Prueba",
    "edad": 23,
    "correo": "malia@mail.com",
    "genero":"Masculino",
    "dni":"1254786895",
    "password":"abc123"
}

###
POST http://localhost:3000/api/auth/singin HTTP/1.1
Content-Type: application/json

{
    "correo": "arturo@mail.com",
    "password": "abc123"
}

### USERS ENDPOINTS 
POST http://localhost:3000/api/users HTTP/1.1